services:
  db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress_dev
    networks:
      - wordpress_net

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress_dev
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpassword
      WORDPRESS_DB_NAME: wordpress_dev
    networks:
      - wordpress_net

  wpcli:
    image: wordpress:cli
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db
      - wordpress
    networks:
      - wordpress_net
    entrypoint: [ 'wp' ]

volumes:
  db_data:

networks:
  wordpress_net:
